export type Slot = { x: number; y: number; w: number; h: number };

export type Card = {
  id: string;
  event: string;
  name: string;
  /** Light image shown in the page. */
  preview: string;
  /** Full-size image used for PNG export; slot coordinates are in its pixels. */
  full: string;
  width: number;
  height: number;
  slots: Slot[];
};

/** Row-major square grid from column lefts and row tops. */
const grid = (lefts: number[], tops: number[], side: number): Slot[] =>
  tops.flatMap((y) => lefts.map((x) => ({ x, y, w: side, h: side })));

/** Poster in public/templates/<folder>/: `<name>.png` for export; `<name>.webp` for display is generated by vite.config.ts. */
const poster = (folder: string, name: string) => ({
  preview: `templates/${folder}/${name}.webp`,
  full: `templates/${folder}/${name}.png`,
});

const screamFortress2026 = grid([221, 817, 1406, 2010, 2605], [745, 1343, 1940, 2532, 3123], 550);

// Newest event first: its cards get quick buttons, and every event is listed in the archive.
// To add a card (including older years): put its PNG in public/templates/<event>/,
// then add an entry here.
export const cards: Card[] = [
  {
    id: "sf2026-1",
    event: "Scream Fortress 2026",
    name: "Card 1",
    ...poster("scream-fortress-2026", "card-1"),
    width: 3448,
    height: 3936,
    slots: screamFortress2026,
  },
  {
    id: "sf2026-2",
    event: "Scream Fortress 2026",
    name: "Card 2",
    ...poster("scream-fortress-2026", "card-2"),
    width: 3448,
    height: 3936,
    slots: screamFortress2026,
  },
];

export const currentEvent = cards[0].event;

export const findCard = (id: string | null): Card => cards.find((card) => card.id === id) ?? cards[0];

/** Cards grouped by event, in registry order. */
export const cardsByEvent = (): Map<string, Card[]> =>
  cards.reduce((groups, card) => groups.set(card.event, [...(groups.get(card.event) ?? []), card]), new Map<string, Card[]>());
