import type { Kind } from "../steam/workshop";

/** `kind` is what the poster's square asks for; without one, the square takes anything (the "?" squares). */
export type Slot = { x: number; y: number; w: number; h: number; kind?: Kind };

export type Card = {
  id: string;
  event: string;
  name: string;
  /** Light image shown in the page. */
  preview: string;
  /** Full-size image used for PNG export; slot coordinates are in its pixels. */
  full: string;
  width: number;
  height: number;
  slots: Slot[];
};

/** Row-major square grid from column lefts and row tops, with the kind each row asks for. */
const grid = (lefts: number[], tops: number[], side: number, rows: Array<Kind | undefined> = []): Slot[] =>
  tops.flatMap((y, row) => lefts.map((x) => ({ x, y, w: side, h: side, kind: rows[row] })));

/** Marks squares as "?": they take any item. */
const wildcards = (slots: Slot[], indexes: number[]): Slot[] =>
  slots.map((slot, index) => indexes.includes(index) ? { ...slot, kind: undefined } : slot);

/** Poster in public/templates/<folder>/: `<name>.png` for export; `<name>.webp` for display is generated by vite.config.ts. */
const poster = (folder: string, name: string) => ({
  preview: `templates/${folder}/${name}.webp`,
  full: `templates/${folder}/${name}.png`,
});

const screamFortress2026 = (rows: Kind[]) => grid([221, 817, 1406, 2010, 2605], [745, 1343, 1940, 2532, 3123], 550, rows);

// Newest event first: it opens by default, and every event is listed in the archive. An event's cards are shown together.
// To add a card (including older years): put its PNG in public/templates/<event>/,
// then add an entry here.
export const cards: Card[] = [
  {
    id: "sf2026-1",
    event: "Scream Fortress 2026",
    name: "Card 1",
    ...poster("scream-fortress-2026", "card-1"),
    width: 3448,
    height: 3936,
    slots: wildcards(screamFortress2026(["War Paint", "War Paint", "War Paint", "Unusual Effect", "Unusual Effect"]), [7, 12]),
  },
  {
    id: "sf2026-2",
    event: "Scream Fortress 2026",
    name: "Card 2",
    ...poster("scream-fortress-2026", "card-2"),
    width: 3448,
    height: 3936,
    slots: screamFortress2026(["Cosmetic", "Cosmetic", "Cosmetic", "Taunt", "Map"]),
  },
];

export const currentEvent = cards[0].event;

/** Cards grouped by event, in registry order. */
export const cardsByEvent = (): Map<string, Card[]> =>
  cards.reduce((groups, card) => groups.set(card.event, [...(groups.get(card.event) ?? []), card]), new Map<string, Card[]>());
